theme: minima
title: My  GitHub journal
author:
  name: Prof Gaëlle
description: > # this means to ignore newlines until "show_excerpts:"
This is my learning journal with open notes on how I have used GitHub and other geeky resources.

show_excerpts: true

# generate social links in footer
  social_links:
    twitter: profgaelle
    github:  profgaelle
    youtube_channel: UCJvWlVgH82jxL8T4AYKTyIg
    youtube_channel_name: profgaelle

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - blog.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag